apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shell-bot
  template:
    metadata:
      labels:
        app: shell-bot
    spec:
      volumes:
        - name: secrets
          secret:
            secretName: shell-bot
      containers:
        - name: shell-bot
          image: europe-west3-docker.pkg.dev/discord-shell-bot/shell-bot/shell-bot:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
          env:
            - name: SHELLBOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: shell-bot
                  key: token
            - name: SHELLBOT_CHANNEL_ID
              valueFrom:
                configMapKeyRef:
                  name: shell-bot
                  key: channel-id
            - name: SHELLBOT_MANAGERS
              valueFrom:
                configMapKeyRef:
                  name: shell-bot
                  key: managers
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: '/secrets/service-account-credentials'
          volumeMounts:
            - mountPath: /secrets/
              name: secrets
