name: CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:
    branches: [ '*' ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        env:
          USERNAME: ${{ secrets.CYLONE_SNAPSHOTS_USERNAME }}
          PASSWORD: ${{ secrets.CYLONE_SNAPSHOTS_PASSWORD }}
        run: >
          ./gradlew build
