name: Deploy to GKE

on:
  workflow_dispatch:

env:
  PROJECT_ID: discord-shell-bot
  GKE_CLUSTER: shell-bot
  GKE_ZONE: europe-west3
  IMAGE_NAME: europe-west3-docker.pkg.dev/discord-shell-bot/shell-bot/shell-bot

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build jar
        run: ./gradlew clean shadowJar

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}

      - name: Build docker image
        run: >
          gcloud builds submit .
          --tag ${{ env.IMAGE_NAME }}

      - name: Deploy to GKE
        run: kubectl apply -f deployment.yml
