name: Deploy infrastucture

on:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Set up terraform'
        uses: hashicorp/setup-terraform@v2

      - name: 'Terraform Init'
        run: cd infrastructure && terraform init

      - name: 'Terraform Apply'
        run: cd infrastructure && terraform apply -auto-approve
